[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.iosevka-custom.variants.design]
v = "straight-serifless"
x = "straight-serifless"
y = "straight-turn-serifless"
brace = "straight"
